#!/bin/bash

terraform state mv data.aws_iam_policy_document.lambda_assume_role_policy_document module.numbers_station.data.aws_iam_policy_document.lambda_assume_role_policy_document

terraform state mv data.aws_iam_policy_document.lambda_role_permissions_policy_document module.numbers_station.data.aws_iam_policy_document.lambda_role_permissions_policy_document

terraform state mv aws_cloudwatch_event_rule.cloudwatch_event_rule module.numbers_station.aws_cloudwatch_event_rule.cloudwatch_event_rule

terraform state mv aws_cloudwatch_event_target.cloudwatch_event_target module.numbers_station.aws_cloudwatch_event_target.cloudwatch_event_target

terraform state mv aws_ecr_lifecycle_policy.repository_lifecycle_policy module.numbers_station.aws_ecr_lifecycle_policy.repository_lifecycle_policy

terraform state mv aws_ecr_repository.repository module.numbers_station.aws_ecr_repository.repository

terraform state mv aws_iam_policy.lambda_role_permissions module.numbers_station.aws_iam_policy.lambda_role_permissions

terraform state mv aws_iam_role.lambda_role module.numbers_station.aws_iam_role.lambda_role

terraform state mv aws_iam_role_policy_attachment.lambda_role_policy_attachment module.numbers_station.aws_iam_role_policy_attachment.lambda_role_policy_attachment

terraform state mv aws_lambda_function.lambda_function module.numbers_station.aws_lambda_function.lambda_function

terraform state mv aws_lambda_permission.lambda_permission_allow_cloudwatch module.numbers_station.aws_lambda_permission.lambda_permission_allow_cloudwatch

terraform state mv aws_secretsmanager_secret.twitter_access_token module.numbers_station.aws_secretsmanager_secret.twitter_access_token

terraform state mv aws_secretsmanager_secret.twitter_access_token_secret module.numbers_station.aws_secretsmanager_secret.twitter_access_token_secret

terraform state mv aws_secretsmanager_secret.twitter_consumer_key module.numbers_station.aws_secretsmanager_secret.twitter_consumer_key

terraform state mv aws_secretsmanager_secret.twitter_consumer_secret module.numbers_station.aws_secretsmanager_secret.twitter_consumer_secret

terraform state mv aws_secretsmanager_secret_version.twitter_access_token_secret_version module.numbers_station.aws_secretsmanager_secret_version.twitter_access_token_secret_version

terraform state mv aws_secretsmanager_secret_version.twitter_access_token_version module.numbers_station.aws_secretsmanager_secret_version.twitter_access_token_version

terraform state mv aws_secretsmanager_secret_version.twitter_consumer_key_version module.numbers_station.aws_secretsmanager_secret_version.twitter_consumer_key_version

terraform state mv aws_secretsmanager_secret_version.twitter_consumer_secret_version module.numbers_station.aws_secretsmanager_secret_version.twitter_consumer_secret_version

